import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  ru: {
    // Hero
    presaleNow: 'Presale Now Live!',
    heroTitle1: 'Auralis',
    heroTitle2: 'Web3 Socialverse',
    heroDescription: 'Чат, где твой 3D-аватар оживает с AI и зарабатывает токены, пока ты спишь. Telegram + NFT + Gaming на блокчейне Aptos.',
    buyARAToken: 'Buy ARA Token',
    learnMore: 'Learn More',
    tokenPrice: 'Token Price',
    totalSupply: 'Total Supply',
    airdrop: 'Airdrop',
    
    // Token Sale
    buyARATokens: 'Buy ARA Tokens',
    secureTokens: 'Secure your tokens at presale price',
    presaleEndsIn: 'Presale Ends In',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    saleProgress: 'Sale Progress',
    sold: 'Sold',
    selectWallet: 'Select Wallet',
    connectWallet: 'Connect',
    connected: 'Connected',
    connectedAddress: 'Connected Address',
    araTokenQuantity: 'ARA Token Quantity',
    enterQuantity: 'Enter quantity (e.g., 1000)',
    pricePerToken: 'Price per token:',
    quantity: 'Quantity:',
    totalCost: 'Total Cost:',
    createPurchaseOrder: 'Create Purchase Order',
    processing: 'Processing...',
    tokensDistributed: 'Tokens will be manually distributed to your wallet after payment confirmation',
    
    // Payment Modal
    orderPayment: 'Оплата заказа',
    transferAmount: 'Переведите',
    toAddress: 'на адрес ниже',
    paymentTime: 'Время на оплату',
    quantityARA: 'Количество ARA:',
    walletAddress: 'Адрес кошелька',
    qrCode: 'QR-код',
    aptosPaymentAddress: 'Aptos (APT) Адрес для оплаты:',
    sendOnlyUSDT: '⚠️ Отправляйте только USDT через сеть Aptos на этот адрес',
    scanQR: 'Отсканируйте QR-код для оплаты',
    paymentInstructions: '📝 Инструкция по оплате:',
    step1: 'Скопируйте адрес кошелька или отсканируйте QR-код',
    step2: 'через сеть Aptos',
    step3: 'Нажмите "Я оплатил" после завершения транзакции',
    step4: 'Ваши токены будут начислены в Q2 2026',
    iPaid: '✓ Я оплатил',
    processingTime: 'После оплаты обработка может занять до 24 часов',
    
    // Success Modal
    paymentReceived: 'Оплата получена!',
    orderProcessed: 'Ваш заказ успешно обработан',
    tokensPurchased: 'Куплено токенов',
    distributionDate: 'Дата начисления',
    tokensWillBe: 'Ваши',
    tokensText: 'токенов',
    autoDistributed: 'будут автоматически начислены на ваш кошелек:',
    expectedDate: 'Ожидаемая дата:',
    aprilJune2026: 'Апрель-Июнь 2026',
    great: 'Отлично!',
    followUpdates: 'Следите за обновлениями в наших соцсетях',
    
    // Features
    whatIsAuralis: 'Что такое Auralis?',
    platformDescription: 'Платформа, которая объединяет мессенджер, NFT-экономику и 3D-игру на блокчейне Aptos',
    web3Messenger: 'Web3 Messenger',
    web3MessengerDesc: 'Чаты, группы, каналы как в Telegram, но с NFT-стикерами и блокчейн-безопасностью',
    '3DAvatars': '3D Avatars',
    '3DAvatarsDesc': 'Создай уникального аватара-NFT с AR-сканом лица. Более 1000 вариантов кастомизации',
    openWorldGame: 'Open World Game',
    openWorldGameDesc: 'Полноценная 3D-игра с открытым миром, где аватары оживают благодаря AI',
    aiPassiveIncome: 'AI Passive Income',
    aiPassiveIncomeDesc: 'Твой аватар зарабатывает 24/7: фармит, торгует, выполняет квесты пока ты спишь',
    
    // Tokenomics
    tokenomics: 'Tokenomics',
    araTokenDistribution: 'ARA Token Distribution',
    communityAirdrop: 'Community & Airdrop',
    teamVested: 'Team (vested)',
    liquidity: 'Liquidity',
    ecosystem: 'Ecosystem',
    marketing: 'Marketing',
    features: '⚡ Особенности',
    feature1: '• 20% токенов для airdrop (ранним юзерам)',
    feature2: '• Burn 0.15% при каждой транзакции (дефляция)',
    feature3: '• Staking APY: 15-25%',
    
    // Roadmap
    roadmap: 'Roadmap',
    pathToMetaverse: 'Путь к полной метавселенной',
    q1_2026: 'Q1 2026',
    messengerLaunch: 'Messenger Launch',
    q1Item1: 'Запуск мессенджера (чаты, группы, каналы)',
    q1Item2: 'Airdrop фаза 1 (100-500 ARA за активность)',
    q1Item3: 'Базовые 3D-аватары',
    q2_2026: 'Q2 2026',
    marketplaceWallet: 'Marketplace & Wallet',
    q2Item1: 'DEX на Aptos для NFT-трейдинга',
    q2Item2: 'Встроенный non-custodial кошелек',
    q2Item3: 'Premium-функции',
    q3_2026: 'Q3 2026',
    '3dIntegration': '3D Integration',
    q3Item1: '3D-видеочаты с аватарами',
    q3Item2: 'AI-агенты beta (автономные действия)',
    q3Item3: 'AR-скан для аватаров',
    q4_2026: 'Q4 2026',
    fullGameLaunch: 'Full Game Launch',
    q4Item1: 'Открытый 3D-мир',
    q4Item2: 'Аватары оживают с AI (24/7)',
    q4Item3: 'Пассивный доход через AI-агентов',
    '2027plus': '2027+',
    expansion: 'Expansion',
    exp1: 'Mobile VR поддержка',
    exp2: 'Cross-chain интеграции',
    exp3: 'Партнерства с брендами (NFT-одежда)',
    
    // Footer
    yourPortal: 'Ваш портал в бесконечную цифровую душу',
    onAptos: 'на блокчейне Aptos',
    links: 'Ссылки',
    buyARA: 'Купить ARA',
    whitepaper: 'Whitepaper',
    documentation: 'Документация',
    faq: 'FAQ',
    socialMedia: 'Социальные сети',
    allRightsReserved: 'All rights reserved.',
  },
  
  en: {
    // Hero
    presaleNow: 'Presale Now Live!',
    heroTitle1: 'Auralis',
    heroTitle2: 'Web3 Socialverse',
    heroDescription: 'A chat where your 3D avatar comes alive with AI and earns tokens while you sleep. Telegram + NFT + Gaming on Aptos blockchain.',
    buyARAToken: 'Buy ARA Token',
    learnMore: 'Learn More',
    tokenPrice: 'Token Price',
    totalSupply: 'Total Supply',
    airdrop: 'Airdrop',
    
    // Token Sale
    buyARATokens: 'Buy ARA Tokens',
    secureTokens: 'Secure your tokens at presale price',
    presaleEndsIn: 'Presale Ends In',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    saleProgress: 'Sale Progress',
    sold: 'Sold',
    selectWallet: 'Select Wallet',
    connectWallet: 'Connect',
    connected: 'Connected',
    connectedAddress: 'Connected Address',
    araTokenQuantity: 'ARA Token Quantity',
    enterQuantity: 'Enter quantity (e.g., 1000)',
    pricePerToken: 'Price per token:',
    quantity: 'Quantity:',
    totalCost: 'Total Cost:',
    createPurchaseOrder: 'Create Purchase Order',
    processing: 'Processing...',
    tokensDistributed: 'Tokens will be manually distributed to your wallet after payment confirmation',
    
    // Payment Modal
    orderPayment: 'Order Payment',
    transferAmount: 'Transfer',
    toAddress: 'to the address below',
    paymentTime: 'Payment Time',
    quantityARA: 'ARA Quantity:',
    walletAddress: 'Wallet Address',
    qrCode: 'QR Code',
    aptosPaymentAddress: 'Aptos (APT) Payment Address:',
    sendOnlyUSDT: '⚠️ Send only USDT via Aptos network to this address',
    scanQR: 'Scan QR code for payment',
    paymentInstructions: '📝 Payment Instructions:',
    step1: 'Copy wallet address or scan QR code',
    step2: 'via Aptos network',
    step3: 'Click "I Paid" after completing transaction',
    step4: 'Your tokens will be credited in Q2 2026',
    iPaid: '✓ I Paid',
    processingTime: 'Processing may take up to 24 hours after payment',
    
    // Success Modal
    paymentReceived: 'Payment Received!',
    orderProcessed: 'Your order has been successfully processed',
    tokensPurchased: 'Tokens Purchased',
    distributionDate: 'Distribution Date',
    tokensWillBe: 'Your',
    tokensText: 'tokens',
    autoDistributed: 'will be automatically credited to your wallet:',
    expectedDate: 'Expected date:',
    aprilJune2026: 'April-June 2026',
    great: 'Great!',
    followUpdates: 'Follow updates on our social media',
    
    // Features
    whatIsAuralis: 'What is Auralis?',
    platformDescription: 'A platform combining messenger, NFT economy, and 3D game on Aptos blockchain',
    web3Messenger: 'Web3 Messenger',
    web3MessengerDesc: 'Chats, groups, channels like Telegram, but with NFT stickers and blockchain security',
    '3DAvatars': '3D Avatars',
    '3DAvatarsDesc': 'Create a unique NFT avatar with AR face scan. Over 1000 customization options',
    openWorldGame: 'Open World Game',
    openWorldGameDesc: 'Full 3D game with open world where avatars come alive thanks to AI',
    aiPassiveIncome: 'AI Passive Income',
    aiPassiveIncomeDesc: 'Your avatar earns 24/7: farms, trades, completes quests while you sleep',
    
    // Tokenomics
    tokenomics: 'Tokenomics',
    araTokenDistribution: 'ARA Token Distribution',
    communityAirdrop: 'Community & Airdrop',
    teamVested: 'Team (vested)',
    liquidity: 'Liquidity',
    ecosystem: 'Ecosystem',
    marketing: 'Marketing',
    features: '⚡ Features',
    feature1: '• 20% tokens for airdrop (early users)',
    feature2: '• Burn 0.15% per transaction (deflationary)',
    feature3: '• Staking APY: 15-25%',
    
    // Roadmap
    roadmap: 'Roadmap',
    pathToMetaverse: 'Path to full metaverse',
    q1_2026: 'Q1 2026',
    messengerLaunch: 'Messenger Launch',
    q1Item1: 'Messenger launch (chats, groups, channels)',
    q1Item2: 'Airdrop phase 1 (100-500 ARA for activity)',
    q1Item3: 'Basic 3D avatars',
    q2_2026: 'Q2 2026',
    marketplaceWallet: 'Marketplace & Wallet',
    q2Item1: 'DEX on Aptos for NFT trading',
    q2Item2: 'Built-in non-custodial wallet',
    q2Item3: 'Premium features',
    q3_2026: 'Q3 2026',
    '3dIntegration': '3D Integration',
    q3Item1: '3D video chats with avatars',
    q3Item2: 'AI agents beta (autonomous actions)',
    q3Item3: 'AR scan for avatars',
    q4_2026: 'Q4 2026',
    fullGameLaunch: 'Full Game Launch',
    q4Item1: 'Open 3D world',
    q4Item2: 'Avatars come alive with AI (24/7)',
    q4Item3: 'Passive income through AI agents',
    '2027plus': '2027+',
    expansion: 'Expansion',
    exp1: 'Mobile VR support',
    exp2: 'Cross-chain integrations',
    exp3: 'Brand partnerships (NFT clothing)',
    
    // Footer
    yourPortal: 'Your gateway to the infinite digital soul',
    onAptos: 'on Aptos blockchain',
    links: 'Links',
    buyARA: 'Buy ARA',
    whitepaper: 'Whitepaper',
    documentation: 'Documentation',
    faq: 'FAQ',
    socialMedia: 'Social Media',
    allRightsReserved: 'All rights reserved.',
  },
  
  es: {
    // Hero
    presaleNow: '¡Preventa en Vivo!',
    heroTitle1: 'Auralis',
    heroTitle2: 'Web3 Socialverse',
    heroDescription: 'Un chat donde tu avatar 3D cobra vida con IA y gana tokens mientras duermes. Telegram + NFT + Gaming en blockchain Aptos.',
    buyARAToken: 'Comprar Token ARA',
    learnMore: 'Más Información',
    tokenPrice: 'Precio del Token',
    totalSupply: 'Suministro Total',
    airdrop: 'Airdrop',
    
    // Token Sale
    buyARATokens: 'Comprar Tokens ARA',
    secureTokens: 'Asegura tus tokens a precio de preventa',
    presaleEndsIn: 'La Preventa Termina En',
    days: 'Días',
    hours: 'Horas',
    minutes: 'Minutos',
    seconds: 'Segundos',
    saleProgress: 'Progreso de Venta',
    sold: 'Vendido',
    selectWallet: 'Seleccionar Cartera',
    connectWallet: 'Conectar',
    connected: 'Conectado',
    connectedAddress: 'Dirección Conectada',
    araTokenQuantity: 'Cantidad de Tokens ARA',
    enterQuantity: 'Ingrese cantidad (ej., 1000)',
    pricePerToken: 'Precio por token:',
    quantity: 'Cantidad:',
    totalCost: 'Costo Total:',
    createPurchaseOrder: 'Crear Orden de Compra',
    processing: 'Procesando...',
    tokensDistributed: 'Los tokens serán distribuidos manualmente a tu cartera después de la confirmación del pago',
    
    // Payment Modal
    orderPayment: 'Pago de Pedido',
    transferAmount: 'Transferir',
    toAddress: 'a la dirección a continuación',
    paymentTime: 'Tiempo de Pago',
    quantityARA: 'Cantidad ARA:',
    walletAddress: 'Dirección de Cartera',
    qrCode: 'Código QR',
    aptosPaymentAddress: 'Dirección de Pago Aptos (APT):',
    sendOnlyUSDT: '⚠️ Envíe solo USDT a través de la red Aptos a esta dirección',
    scanQR: 'Escanee el código QR para pagar',
    paymentInstructions: '📝 Instrucciones de Pago:',
    step1: 'Copie la dirección de la cartera o escanee el código QR',
    step2: 'a través de la red Aptos',
    step3: 'Haga clic en "Ya Pagué" después de completar la transacción',
    step4: 'Sus tokens serán acreditados en Q2 2026',
    iPaid: '✓ Ya Pagué',
    processingTime: 'El procesamiento puede tardar hasta 24 horas después del pago',
    
    // Success Modal
    paymentReceived: '¡Pago Recibido!',
    orderProcessed: 'Su pedido ha sido procesado exitosamente',
    tokensPurchased: 'Tokens Comprados',
    distributionDate: 'Fecha de Distribución',
    tokensWillBe: 'Tus',
    tokensText: 'tokens',
    autoDistributed: 'serán acreditados automáticamente a tu cartera:',
    expectedDate: 'Fecha esperada:',
    aprilJune2026: 'Abril-Junio 2026',
    great: '¡Excelente!',
    followUpdates: 'Sigue las actualizaciones en nuestras redes sociales',
    
    // Features
    whatIsAuralis: '¿Qué es Auralis?',
    platformDescription: 'Una plataforma que combina mensajería, economía NFT y juego 3D en blockchain Aptos',
    web3Messenger: 'Mensajero Web3',
    web3MessengerDesc: 'Chats, grupos, canales como Telegram, pero con stickers NFT y seguridad blockchain',
    '3DAvatars': 'Avatares 3D',
    '3DAvatarsDesc': 'Crea un avatar NFT único con escaneo facial AR. Más de 1000 opciones de personalización',
    openWorldGame: 'Juego de Mundo Abierto',
    openWorldGameDesc: 'Juego 3D completo con mundo abierto donde los avatares cobran vida gracias a la IA',
    aiPassiveIncome: 'Ingresos Pasivos con IA',
    aiPassiveIncomeDesc: 'Tu avatar gana 24/7: farmea, comercia, completa misiones mientras duermes',
    
    // Tokenomics
    tokenomics: 'Tokenomics',
    araTokenDistribution: 'Distribución de Token ARA',
    communityAirdrop: 'Comunidad y Airdrop',
    teamVested: 'Equipo (adquirido)',
    liquidity: 'Liquidez',
    ecosystem: 'Ecosistema',
    marketing: 'Marketing',
    features: '⚡ Características',
    feature1: '• 20% de tokens para airdrop (usuarios tempranos)',
    feature2: '• Quema del 0.15% por transacción (deflacionario)',
    feature3: '• APY de Staking: 15-25%',
    
    // Roadmap
    roadmap: 'Hoja de Ruta',
    pathToMetaverse: 'Camino al metaverso completo',
    q1_2026: 'Q1 2026',
    messengerLaunch: 'Lanzamiento del Mensajero',
    q1Item1: 'Lanzamiento del mensajero (chats, grupos, canales)',
    q1Item2: 'Fase 1 de airdrop (100-500 ARA por actividad)',
    q1Item3: 'Avatares 3D básicos',
    q2_2026: 'Q2 2026',
    marketplaceWallet: 'Mercado y Cartera',
    q2Item1: 'DEX en Aptos para trading NFT',
    q2Item2: 'Cartera no custodial integrada',
    q2Item3: 'Funciones premium',
    q3_2026: 'Q3 2026',
    '3dIntegration': 'Integración 3D',
    q3Item1: 'Videochats 3D con avatares',
    q3Item2: 'Agentes IA beta (acciones autónomas)',
    q3Item3: 'Escaneo AR para avatares',
    q4_2026: 'Q4 2026',
    fullGameLaunch: 'Lanzamiento del Juego Completo',
    q4Item1: 'Mundo 3D abierto',
    q4Item2: 'Avatares cobran vida con IA (24/7)',
    q4Item3: 'Ingresos pasivos a través de agentes IA',
    '2027plus': '2027+',
    expansion: 'Expansión',
    exp1: 'Soporte para VR móvil',
    exp2: 'Integraciones cross-chain',
    exp3: 'Asociaciones de marcas (ropa NFT)',
    
    // Footer
    yourPortal: 'Tu portal al alma digital infinita',
    onAptos: 'en blockchain Aptos',
    links: 'Enlaces',
    buyARA: 'Comprar ARA',
    whitepaper: 'Whitepaper',
    documentation: 'Documentación',
    faq: 'Preguntas Frecuentes',
    socialMedia: 'Redes Sociales',
    allRightsReserved: 'Todos los derechos reservados.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('auralis_language');
    return saved || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('auralis_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
